import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Fake Twitter</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

<h1>Fake Twitter</h1>

    </div>
  )
}
